"""
    Unison public API

    API for Python and R libraries  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auto_api_client
from auto_api_client.model.public_cohort_execute_query_request import PublicCohortExecuteQueryRequest


class TestPublicCohortExecuteQueryRequest(unittest.TestCase):
    """PublicCohortExecuteQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicCohortExecuteQueryRequest(self):
        """Test PublicCohortExecuteQueryRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PublicCohortExecuteQueryRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
