"""
    Unison public API

    API for Python and R libraries  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import auto_api_client
from auto_api_client.api.public_api_api import PublicAPIApi  # noqa: E501


class TestPublicAPIApi(unittest.TestCase):
    """PublicAPIApi unit test stubs"""

    def setUp(self):
        self.api = PublicAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_public_cohort_execute_query(self):
        """Test case for public_cohort_execute_query

        """
        pass


if __name__ == '__main__':
    unittest.main()
