version: '3'

services:
  unison-python-sdk:
    build:
      context: .
      dockerfile: Resources/docker/Dockerfile
    volumes:
      - ./:/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'